spring:
  jpa:
    generate-ddl: 'false'
    database: postgresql
    hibernate:
      ddl-auto: none
  main:
    allow-circular-references: true
  application:
    name: auth-service
  profiles:
    active: prod
  datasource:
    password: admin
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/nms_auth_service

server:
  port: 9090

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
      springframework:
        security: DEBUG

security:
  jwt:
    secret: a2pzZGRnaGh2LGRtZmJhbGtqYmphZmJrcic7bmEgLCdlbWI7ZWFqaHJnaWhhZWk7b3Z1c2F2ay8uYW1ibHRyd2hp
    access: 600000
    refresh: 2592000000